# model: "FastSpeech"

labels: [
    ' ', '!', '"', "'", '(', ')', ',', '-', '.', ':', ';', '?', 'A', 'B',
    'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
    'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', 'a', 'b',
    'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p',
    'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
]

AudioToMelSpectrogramPreprocessor:
    normalize: null
    window_size: null
    window_stride: null
    n_window_size: 1024
    n_window_stride: 256
    window: "hann"
    features: 80
    n_fft: 1024
    frame_splicing: 1
    dither: 0.
    feat_type: "logfbank"
    stft_conv: true
    sample_rate: 22050
    highfreq: 8000
    preemph: null
    pad_value: -11.52
    mag_power: 1.
    log_zero_guard_type: "clamp"
    log_zero_guard_value: 1.0e-5